USE bd_rede_postos

CREATE OR ALTER PROCEDURE SP_OLTP_TIPO_PAGAMENTO (@DATA_CARGA DATETIME) AS
BEGIN
	DELETE TB_AUX_TIPO_PAGAMENTO WHERE DATA_CARGA = @DATA_CARGA

	INSERT INTO TB_AUX_TIPO_PAGAMENTO
	SELECT @DATA_CARGA, COD_TIPO_PAGAMENTO, TIPO_PAGAMENTO FROM TB_TIPO_PAGAMENTO
END
