USE bd_rede_postos

CREATE OR ALTER PROCEDURE SP_OLTP_VENDA (@DATA_CARGA DATETIME, @DT_INICIAL DATETIME, @DT_FINAL DATETIME) AS
BEGIN
	DELETE TB_AUX_VENDA WHERE DATA_CARGA = @DATA_CARGA

	INSERT INTO TB_AUX_VENDA
	SELECT @DATA_CARGA, V.DATA_VENDA, V.COD_VENDA, V.COD_LOJA, V.COD_FUNCIONARIO ,V.COD_PRODUTO,
	V.COD_TIPO_PAGAMENTO, V.VOLUME, V.VALOR
	FROM TB_VENDA V WHERE V.DATA_VENDA >= @DT_INICIAL AND V.DATA_VENDA <= @DT_FINAL
END