USE bd_rede_postos

CREATE OR ALTER PROCEDURE SP_OLTP_LOJA (@DATA_CARGA DATETIME) AS
BEGIN
	DELETE TB_AUX_LOJA WHERE DATA_CARGA = @DATA_CARGA

	INSERT INTO TB_AUX_LOJA
	SELECT @DATA_CARGA, L.COD_LOJA, L.NM_LOJA, 
	F.NM_FUNCIONARIO, C.CIDADE,
	E.ESTADO, E.SIGLA
	FROM TB_LOJA L INNER JOIN TB_FUNCIONARIO F
	ON(L.COD_GERENTE = F.COD_FUNCIONARIO)
	INNER JOIN TB_CIDADE C
	ON(L.COD_CIDADE = C.COD_CIDADE)
	INNER JOIN TB_ESTADO E
	ON(C.COD_ESTADO = E.COD_ESTADO)
END

SELECT * FROM TB_AUX_LOJA
SELECT * FROM TB_LOJA
SELECT * FROM TB_CIDADE
SELECT * FROM TB_FUNCIONARIO F INNER JOIN TB_CARGO C ON(F.COD_CARGO = C.COD_CARGO)