
USE bd_rede_postos

CREATE OR ALTER PROCEDURE SP_OLTP_FUNCIONARIO (@DATA_CARGA DATETIME) AS
BEGIN
	DELETE TB_AUX_FUNCIONARIO WHERE DATA_CARGA = @DATA_CARGA

	INSERT INTO TB_AUX_FUNCIONARIO 
	SELECT @DATA_CARGA, F.COD_FUNCIONARIO, F.NM_FUNCIONARIO, C.COD_CARGO, C.NM_CARGO
	FROM TB_FUNCIONARIO F INNER JOIN TB_CARGO C
	ON (F.COD_CARGO = C.COD_CARGO)
END

SELECT * FROM TB_AUX_FUNCIONARIO
SELECT * FROM TB_FUNCIONARIO