USE bd_rede_postos

CREATE OR ALTER PROCEDURE SP_OLTP_PRODUTO (@DATA_CARGA DATETIME) AS
BEGIN
	DELETE TB_AUX_PRODUTO WHERE DATA_CARGA = @DATA_CARGA

	INSERT INTO TB_AUX_PRODUTO
	SELECT @DATA_CARGA, P.COD_PRODUTO, P.PRODUTO, P.COD_SUBCATEGORIA,
	S.SUBCATEGORIA, S.COD_CATEGORIA, C.CATEGORIA
	FROM TB_PRODUTO P INNER JOIN TB_SUBCATEGORIA S
	ON(P.COD_SUBCATEGORIA = S.COD_SUBCATEGORIA) INNER JOIN TB_CATEGORIA C
	ON(S.COD_CATEGORIA = C.COD_CATEGORIA)
END

SELECT * FROM TB_AUX_PRODUTO
SELECT * FROM TB_PRODUTO
SELECT * FROM TB_CATEGORIA
SELECT * FROM TB_SUBCATEGORIA