USE bd_rede_postos

CREATE OR ALTER PROCEDURE SP_TESTE_CARGA_OLTP (@DATA_CARGA DATETIME) AS
BEGIN
	EXEC SP_OLTP_VENDA @DATA_CARGA
	EXEC SP_OLTP_TIPO_PAGAMENTO @DATA_CARGA
	EXEC SP_OLTP_PRODUTO @DATA_CARGA
	EXEC SP_OLTP_LOJA @DATA_CARGA, '20210101', '20210101'
	EXEC SP_OLTP_FUNCIONARIO @DATA_CARGA
END

EXEC SP_TESTE_CARGA_OLTP '20210101'
SELECT * FROM TB_AUX_FUNCIONARIO
SELECT * FROM TB_AUX_LOJA
SELECT * FROM TB_AUX_PRODUTO
SELECT * FROM TB_AUX_TIPO_PAGAMENTO
SELECT * FROM TB_AUX_VENDA