USE bd_rede_postos

CREATE OR ALTER PROCEDURE SP_DIM_TIPO_PAGAMENTO (@DATA_CARGA DATETIME) AS
BEGIN
	DECLARE @COD_TIPO_PAGAMENTO INT, @TIPO_PAGAMENTO VARCHAR(50)

	DECLARE C_TIPO_PAGAMENTO CURSOR FOR SELECT COD_TIPO_PAGAMENTO, TIPO_PAGAMENTO 
	FROM TB_AUX_TIPO_PAGAMENTO WHERE DATA_CARGA = @DATA_CARGA

	OPEN C_TIPO_PAGAMENTO
	FETCH C_TIPO_PAGAMENTO INTO @COD_TIPO_PAGAMENTO, @TIPO_PAGAMENTO
	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		-- UPDATE
		IF EXISTS (SELECT COD_TIPO_PAGAMENTO FROM DIM_TIPO_PAGAMENTO WHERE COD_TIPO_PAGAMENTO = @COD_TIPO_PAGAMENTO)
		BEGIN
			UPDATE DIM_TIPO_PAGAMENTO SET COD_TIPO_PAGAMENTO = @COD_TIPO_PAGAMENTO, TIPO_PAGAMENTO = @TIPO_PAGAMENTO
			WHERE COD_TIPO_PAGAMENTO = @COD_TIPO_PAGAMENTO
		END
		-- INSERT
		ELSE
		BEGIN
			INSERT INTO DIM_TIPO_PAGAMENTO VALUES(@COD_TIPO_PAGAMENTO, @TIPO_PAGAMENTO)
		END
		FETCH C_TIPO_PAGAMENTO INTO @COD_TIPO_PAGAMENTO, @TIPO_PAGAMENTO
	END
	CLOSE C_TIPO_PAGAMENTO
	DEALLOCATE C_TIPO_PAGAMENTO
END