USE bd_rede_postos

CREATE OR ALTER PROCEDURE SP_DIM_FUNCIONARIO (@DATA_CARGA DATETIME) AS
BEGIN
	DECLARE @COD_FUNCIONARIO INT, @FUNCIONARIO VARCHAR(100),
	@COD_CARGO INT, @CARGO VARCHAR(100)
	
	DECLARE C_FUNCIONARIO CURSOR FOR SELECT COD_FUNCIONARIO, FUNCIONARIO, COD_CARGO, CARGO FROM TB_AUX_FUNCIONARIO
	WHERE DATA_CARGA = @DATA_CARGA

	OPEN C_FUNCIONARIO
	FETCH C_FUNCIONARIO INTO @COD_FUNCIONARIO, @FUNCIONARIO, @COD_CARGO, @CARGO
	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		-- UPDATE
		IF EXISTS (SELECT COD_FUNCIONARIO FROM DIM_FUNCIONARIO WHERE COD_FUNCIONARIO = @COD_FUNCIONARIO)
		BEGIN
			UPDATE DIM_FUNCIONARIO SET COD_FUNCIONARIO = @COD_FUNCIONARIO, FUNCIONARIO = @FUNCIONARIO,
				   COD_CARGO = @COD_CARGO, CARGO = @CARGO WHERE COD_FUNCIONARIO = @COD_FUNCIONARIO
		END
		-- INSERT
		ELSE
		BEGIN
			INSERT INTO DIM_FUNCIONARIO VALUES(@COD_FUNCIONARIO, @FUNCIONARIO, @COD_CARGO, @CARGO)
		END
		FETCH C_FUNCIONARIO INTO @COD_FUNCIONARIO, @FUNCIONARIO, @COD_CARGO, @CARGO
	END
	CLOSE C_FUNCIONARIO
	DEALLOCATE C_FUNCIONARIO
END
