USE bd_rede_postos

CREATE OR ALTER PROCEDURE SP_DIM_LOJA (@DATA_CARGA DATETIME) AS
BEGIN
	DECLARE @COD_LOJA INT, @LOJA VARCHAR(100), @GERENTE VARCHAR(100),
	@CIDADE VARCHAR(100), @ESTADO VARCHAR(100), @SIGLA_ESTADO VARCHAR(2)

	DECLARE C_LOJA CURSOR FOR SELECT COD_LOJA, LOJA, GERENTE, CIDADE, ESTADO, SIGLA_ESTADO FROM TB_AUX_LOJA
	OPEN C_LOJA
	FETCH C_LOJA INTO @COD_LOJA, @LOJA, @GERENTE, @CIDADE, @ESTADO, @SIGLA_ESTADO
	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		-- UPDATE
		IF EXISTS (SELECT COD_LOJA FROM DIM_LOJA WHERE COD_LOJA = @COD_LOJA)
		BEGIN
				DECLARE @LOJA_AUX VARCHAR(100), @GERENTE_AUX VARCHAR(100),
				@CIDADE_AUX VARCHAR(100), @ESTADO_AUX VARCHAR(100), @SIGLA_ESTADO_AUX VARCHAR(2)
				
				SET @LOJA_AUX = (SELECT LOJA FROM DIM_LOJA WHERE COD_LOJA = @COD_LOJA AND FL_CORRENTE = 'SIM')
				SET @GERENTE_AUX = (SELECT GERENTE FROM DIM_LOJA WHERE COD_LOJA = @COD_LOJA AND FL_CORRENTE = 'SIM')
				SET @CIDADE_AUX = (SELECT CIDADE FROM DIM_LOJA WHERE COD_LOJA = @COD_LOJA AND FL_CORRENTE = 'SIM')
				SET @ESTADO_AUX = (SELECT ESTADO FROM DIM_LOJA WHERE COD_LOJA = @COD_LOJA AND FL_CORRENTE = 'SIM')
				SET @SIGLA_ESTADO_AUX = (SELECT SIGLA_ESTADO FROM DIM_LOJA WHERE COD_LOJA = @COD_LOJA AND FL_CORRENTE = 'SIM')


				IF (@LOJA_AUX != @LOJA) OR (@GERENTE_AUX != @GERENTE) OR (@CIDADE_AUX != @CIDADE) OR
				   (@ESTADO_AUX != @ESTADO) OR (@SIGLA_ESTADO_AUX != @SIGLA_ESTADO_AUX)
				BEGIN
					UPDATE DIM_LOJA SET DT_FIM = @DATA_CARGA, FL_CORRENTE = 'NAO' WHERE COD_LOJA = @COD_LOJA AND FL_CORRENTE = 'SIM'
					
					INSERT INTO DIM_LOJA VALUES(@COD_LOJA, 
					@LOJA, @GERENTE, @CIDADE, @ESTADO, @SIGLA_ESTADO, @DATA_CARGA, NULL, 'SIM')
				END
		END
		-- INSERT
		ELSE
		BEGIN
			INSERT INTO DIM_LOJA VALUES(@COD_LOJA, 
					@LOJA, @GERENTE, @CIDADE, @ESTADO, @SIGLA_ESTADO, @DATA_CARGA, NULL, 'SIM')
		END
		FETCH C_LOJA INTO @COD_LOJA, @LOJA, @GERENTE, @CIDADE, @ESTADO, @SIGLA_ESTADO
	END
	CLOSE C_LOJA
	DEALLOCATE C_LOJA
END
