USE bd_rede_postos

CREATE OR ALTER PROCEDURE SP_FATO_VENDA (@DATA_CARGA DATETIME) AS
BEGIN
	DECLARE @DATA_VENDA DATETIME, @COD_VENDA INT, @COD_LOJA INT, @COD_FUNCIONARIO INT,
	@COD_PRODUTO INT, @COD_TIPO_PAGAMENTO INT, @VOLUME NUMERIC(10,2),
	@VALOR NUMERIC(10,2)

	DECLARE C_VENDA CURSOR FOR SELECT V.DATA_VENDA, V.COD_VENDA, V.COD_LOJA, V.COD_FUNCIONARIO,
	V.COD_PRODUTO, V.COD_TIPO_PAGAMENTO, V.VOLUME, V.VALOR FROM TB_AUX_VENDA V
	WHERE V.DATA_CARGA = @DATA_CARGA

	OPEN C_VENDA
	FETCH C_VENDA INTO @DATA_VENDA, @COD_VENDA, @COD_LOJA, @COD_FUNCIONARIO, @COD_PRODUTO, 
	@COD_TIPO_PAGAMENTO, @VOLUME, @VALOR
	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		
		DECLARE @DATA_VENDA_ID INT, @COD_LOJA_ID INT, @COD_FUNCIONARIO_ID INT,
		@COD_TIPO_PAGAMENTO_ID INT, @COD_TIPO_PRODUTO_ID INT

		SET @DATA_VENDA_ID = (SELECT ID_TEMPO FROM DIM_TEMPO WHERE DATA = @DATA_VENDA)

		IF @DATA_VENDA_ID IS NOT NULL
		BEGIN
			SET @DATA_VENDA_ID = (SELECT ID_TEMPO FROM DIM_TEMPO WHERE DATA = @DATA_VENDA)
		END
		ELSE
		BEGIN
			INSERT INTO TB_VIO_VENDA VALUES(@DATA_CARGA, @DATA_VENDA, 
											@COD_VENDA, @COD_LOJA,
											@COD_FUNCIONARIO, @COD_PRODUTO,
											@COD_TIPO_PAGAMENTO, @VOLUME, @VALOR)
		END

		FETCH C_VENDA INTO @DATA_VENDA, @COD_LOJA, @COD_FUNCIONARIO, @COD_PRODUTO, 
		@COD_TIPO_PAGAMENTO, @VOLUME, @VALOR
	END
	CLOSE C_VENDA
	DEALLOCATE C_VENDA
END

SELECT * FROM TB_AUX_VENDA